name: Deploy Echo State to Novu

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync State to Novu
        uses: novuhq/actions-echo-sync@v0.0.4
        with:
          novu-api-key: ${{secrets.NOVU_API_KEY}}
          echo-url: "https://anonympia.vercel.app/api/echo"
          backend-url: "https://api.novu.co/"

